"use-strict";
// Button assignments
const btnRock = document.querySelector(".btn_rock");
const btnPaper = document.querySelector(".btn_paper");
const btnScissors = document.querySelector(".btn_scissors");
const gameResult = document.querySelector("#result");

//adding event listeners to the buttons and when clicked run the function assigned to each button on page
btnRock.addEventListener("click", () => {
  playRound("rock");
});
btnPaper.addEventListener("click", () => {
  playRound("paper");
});
btnScissors.addEventListener("click", () => {
  playRound("scissors");
});

// Function to generate random numbers in this case to generate random choice from array["rock", "paper", "scissors"]
function aiPlayer() {
  const choices = ["rock", "paper", "scissors"];
  // Use math methods to randomise the chosen content from the array
  const randomNumber = Math.floor(Math.random() * choices.length);
  return choices[randomNumber];
}
// console.log(aiPlayer("paper"));

// Function assigned to each click event when player clicks player choice a random choice is generated by the aiPlayer
function playRound(playerSelection) {
  const aiSelection = aiPlayer();

  // If player selects rock or paper or scissors and AI selects it's choice then check will be run and result will be logged
  if (playerSelection === "rock" || "paper" || "scissors") {
    if (aiSelection === "paper") {
      // Adding result to the result window to display outcome on page
      gameResult.textContent = "You lose! Paper beats rock!";
      console.log("You lose! Paper beats rock!");
    } else if (aiSelection === "scissors") {
      gameResult.textContent = "You win! Rock beats scissors";
      console.log("You win! Rock beats scissors");
    } else {
      gameResult.textContent = "it's a tie! No one wins and no one loses!";
      console.log("It's a tie!");
    }
  }
}
